/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universalinterfacegui;

import java.util.Objects;
import java.util.Observable;

/**
 *
 * @author administrator
 */
public class LotteryGameUniversalGUI extends javax.swing.JFrame {

    /**
     * Creates new form LotteryGameUniversalGUI
     */
    public LotteryGameUniversalGUI() {
        initComponents();
        System.out.println("LotteryGameUniversalGUI Initializing");
        
        UniversalInterfaceObserver universalOutputConsoleObserver = new UniversalInterfaceObserver(universalOutputConsole);
        universalOutputConsole.toString();
        UniversalInterfaceObserver specializedGameInterfacePanelObserver = new UniversalInterfaceObserver(specializedGameInterfacePanel);
        UniversalInterfaceObserver standardButtonLeftObserver = new UniversalInterfaceObserver(standardButtonLeft);
        UniversalInterfaceObserver standardButtonRightObserver = new UniversalInterfaceObserver(standardButtonRight);
        Observable guiSubjectObservable = new Observable();
        guiSubjectObservable.addObserver(universalOutputConsoleObserver);
        guiSubjectObservable.notifyObservers();
        
        System.out.println("LotteryGameUniversalGUI Initialized");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        universalContentPane = new javax.swing.JScrollPane();
        universalOutputConsole = new javax.swing.JTextArea();
        standardButtonLeft = new javax.swing.JButton();
        standardButtonRight = new javax.swing.JButton();
        specializedGameInterfacePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 300));

        universalContentPane.setMaximumSize(new java.awt.Dimension(400, 300));
        universalContentPane.setMinimumSize(new java.awt.Dimension(400, 300));

        universalOutputConsole.setColumns(20);
        universalOutputConsole.setRows(5);
        universalContentPane.setViewportView(universalOutputConsole);

        standardButtonLeft.setText("Start");

        standardButtonRight.setText("Set Button");
        standardButtonRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardButtonRightActionPerformed(evt);
            }
        });

        specializedGameInterfacePanel.setBackground(new java.awt.Color(232, 232, 232));

        javax.swing.GroupLayout specializedGameInterfacePanelLayout = new javax.swing.GroupLayout(specializedGameInterfacePanel);
        specializedGameInterfacePanel.setLayout(specializedGameInterfacePanelLayout);
        specializedGameInterfacePanelLayout.setHorizontalGroup(
            specializedGameInterfacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );
        specializedGameInterfacePanelLayout.setVerticalGroup(
            specializedGameInterfacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(universalContentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(specializedGameInterfacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(standardButtonLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(standardButtonRight, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(specializedGameInterfacePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(universalContentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(standardButtonLeft)
                    .addComponent(standardButtonRight))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void standardButtonRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardButtonRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_standardButtonRightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LotteryGameUniversalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LotteryGameUniversalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LotteryGameUniversalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LotteryGameUniversalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LotteryGameUniversalGUI().setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel specializedGameInterfacePanel;
    private javax.swing.JButton standardButtonLeft;
    private javax.swing.JButton standardButtonRight;
    private javax.swing.JScrollPane universalContentPane;
    private javax.swing.JTextArea universalOutputConsole;
    // End of variables declaration//GEN-END:variables



}
